/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenLocal()
    maven {
        url = uri('https://repo.maven.apache.org/maven2/')
    }
}

dependencies {
    api libs.org.springframework.boot.spring.boot.starter.web
    api libs.net.logstash.logback.logstash.logback.encoder
    testImplementation libs.junit.junit
}

group = 'com.example'
version = '1.1.0-SNAPSHOT'
description = 'java-maven-app'
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications {
        maven(MavenPublication) {
          artifact("build/libs/java-maven-app-master $version"+".jar"){
          extension 'jar'
          }
        }
    }
    repositories{
        maven{
            name 'nexus'
            // url"http://[nexus ip][nexusport]/repositiry/maven-snapshots"
            url"http://157.239.22.19:8081/repositiry/maven-snapshots"
            allowInsecureProtocol = true
            credentials{
                username project.repoUser
                password project.repoPassword
            }
        }
    }
}

-------------------------------------------------------
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = 'java-maven-app'

      
